chore(deps-dev): bump mermaid from 9.1.7 to 9.2.2
Bumps [mermaid](https://github.com/mermaid-js/mermaid)
from 9.1.7 to 9.2.2.
  - [Release notes](https://github.com/mermaid-js/mermaid/releases)
  - [Commits][1]

[1]: https://github.com/mermaid-js/mermaid/compare/9.1.7...9.2.2

The tests needed to be modified slightly, since the following
error is now thrown for our invalid mermaid file test:

```
Error: No diagram type detected for text: ...
```

Co-authored-by: Mindaugas Laganeckas <mindaugas.laganeckas@gmail.com>