chore(deps): bump mermaid to v9.2.0-rc8
Bumps Mermaid to v9.2.0-rc8 as a preparation for v9.2.0

The tests needed to be modified slightly, since the following
error is now thrown for our invalid mermaid file test:

```
Error: No diagram type detected for text: ...
```